apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: ctfd
  name: ctfd
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/issue-temporary-certificate: "true"
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ctfd
                port:
                  number: 80
