kind: Service
apiVersion: v1
metadata:
  name: multi-juicer-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/instance: wrongsecrets-ctf-party
    app.kubernetes.io/name: wrongsecrets-ctf-party
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
