apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: wrongsecrets-balancer
  labels:
    helm.sh/chart: {{ include "wrongsecrets-ctf-party.chart" . }}
rules:
  - apiGroups: ['apps']
    resources: ['deployments']
    verbs: ['get', 'create', 'list', 'delete', 'patch', 'watch', 'update']
  - apiGroups: [''] # "" indicates the core API group
    resources: ['services']
    verbs: ['get', 'create', 'delete']
  - apiGroups: [''] # "" indicates the core API group
    resources: ['pods']
    verbs: ['create', 'get', 'list', 'delete']
  - apiGroups: [''] # "" indicates the core API group
    resources: ['namespaces']
    verbs: ['get', 'create', 'list', 'delete', 'patch', 'watch', 'update']