apiVersion: v1
kind: ConfigMap
metadata:
  name: juice-shop-config
  labels:
    helm.sh/chart: {{ include "wrongsecrets-ctf.chart" . }}
data:
  multi-juicer.yaml: |-
{{ .Values.wrongsecrets.config | indent 4 }}
