{
 "title": "MultiJuicer - Instance Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "difficulties",
    "label": "Difficulty Levels supported by JuiceShop",
    "query": "1,2,3,4,5,6"
   },
   {
    "name": "team",
    "label": "Team",
    "query": "label_values(juiceshop_challenges_total, team)"
   }
  ]
 },
 "panels": [
  { "title": "Challenge Progress", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Solved $difficulties Star Challenges",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "repeat": "difficulties",
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum without (category)(juiceshop_challenges_solved{team=\"$team\", difficulty=\"$difficulties\"}) / sum without (category)(juiceshop_challenges_total{team=\"$team\", difficulty=\"$difficulties\"}) * 100"
    }
   ]
  },
  {
   "title": "Solved $difficulties Star Challenges",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum without (category)(juiceshop_challenges_solved{team=\"$team\", difficulty=\"$difficulties\"}) / sum without (category)(juiceshop_challenges_total{team=\"$team\", difficulty=\"$difficulties\"}) * 100"
    }
   ]
  },
  {
   "title": "Solved $difficulties Star Challenges",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum without (category)(juiceshop_challenges_solved{team=\"$team\", difficulty=\"$difficulties\"}) / sum without (category)(juiceshop_challenges_total{team=\"$team\", difficulty=\"$difficulties\"}) * 100"
    }
   ]
  },
  {
   "title": "Solved $difficulties Star Challenges",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum without (category)(juiceshop_challenges_solved{team=\"$team\", difficulty=\"$difficulties\"}) / sum without (category)(juiceshop_challenges_total{team=\"$team\", difficulty=\"$difficulties\"}) * 100"
    }
   ]
  },
  {
   "title": "Solved $difficulties Star Challenges",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum without (category)(juiceshop_challenges_solved{team=\"$team\", difficulty=\"$difficulties\"}) / sum without (category)(juiceshop_challenges_total{team=\"$team\", difficulty=\"$difficulties\"}) * 100"
    }
   ]
  },
  {
   "title": "Solved $difficulties Star Challenges",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum without (category)(juiceshop_challenges_solved{team=\"$team\", difficulty=\"$difficulties\"}) / sum without (category)(juiceshop_challenges_total{team=\"$team\", difficulty=\"$difficulties\"}) * 100"
    }
   ]
  },
  {
   "title": "Solved Challenges by Category",
   "type": "stat",
   "gridPos": { "h": 4, "w": 19, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by (category)(juiceshop_challenges_solved{team=\"$team\"}) / sum by (category)(juiceshop_challenges_total{team=\"$team\"}) * 100 != 0",
     "legendFormat": "{{category}} "
    }
   ]
  },
  {
   "title": "Cheat Score",
   "type": "stat",
   "description": "The cheat score show a estimate of how likely it is that a team is cheating. This estimate is based on the time taken between challenges solved. Take this only as a approximation and never as direct prove that a team is in fact cheating.",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "juiceshop_cheat_score{team=\"$team\"}"
    }
   ]
  },
  {
   "title": "Business Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Social Interactions",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Orders per Minute" }
     ],
     "targets": [
      {
       "expr": "juiceshop_user_social_interactions{team=\"$team\"}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "User Signups",
     "type": "graph",
     "gridPos": { "h": 6, "w": 16, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(juiceshop_users_registered{team=\"$team\"}[1m])",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 8, "x": 16, "y": 15 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "juiceshop_users_registered{type=\"standard\", team=\"$team\"}"
      }
     ]
    },
    {
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 8, "x": 16, "y": 18 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "juiceshop_users_registered{type=\"deluxe\", team=\"$team\"}"
      }
     ]
    }
   ]
  },
  { "title": "Technical", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "HTTP Requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short", "label": "Requests per Minute" }
   ],
   "targets": [
    {
     "expr": "increase(http_requests_count{app=\"juiceshop\", team=\"$team\"}[1m])",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Process CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "irate(process_cpu_user_seconds_total{team=~\"$team\"}[2m]) * 100",
     "legendFormat": "User CPU"
    },
    {
     "expr": "irate(process_cpu_system_seconds_total{team=~\"$team\"}[2m]) * 100",
     "legendFormat": "Sys CPU"
    }
   ]
  },
  {
   "title": "Event Loop Lag",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 10, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "nodejs_eventloop_lag_seconds{team=~\"$team\"}",
     "legendFormat": "{{team}}"
    }
   ]
  },
  {
   "title": "Process Restart Times",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 17 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(changes(process_start_time_seconds{team=~\"$team\"}[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node.js Version",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 21 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "sum(nodejs_version_info{team=~\"$team\"}) by (version)",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Process Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{team=~\"$team\"}",
     "legendFormat": "Process Memory"
    },
    {
     "expr": "nodejs_heap_size_total_bytes{team=~\"$team\"}",
     "legendFormat": "Heap Total"
    },
    {
     "expr": "nodejs_heap_size_used_bytes{team=~\"$team\"}",
     "legendFormat": "Heap Used"
    },
    {
     "expr": "nodejs_external_memory_bytes{team=~\"$team\"}",
     "legendFormat": "External Memory"
    }
   ]
  },
  {
   "title": "Active Handlers/Requests Total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nodejs_active_handles_total{team=~\"$team\"}",
     "legendFormat": "Active Handler"
    },
    {
     "expr": "nodejs_active_requests_total{team=~\"$team\"}",
     "legendFormat": "Active Request"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "{app=\"juice-shop\", team=\"$team\"}"
    }
   ]
  }
 ]
}