apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: wrongsecrets-gcp-secretsmanager
  namespace: kak
spec:
  provider: gcp
  parameters:
    secrets: |
      - resourceName: "projects/owasp-wrongsecrets/secrets/wrongsecret-1/versions/latest"
        fileName: "wrongsecret"
      - resourceName: "projects/owasp-wrongsecrets/secrets/wrongsecret-2/versions/latest"
        fileName: "wrongsecret-2"
